import path from "node:path";

import type { Plan } from "./types.ts";

const HEADER_LINES: string[] = [
  "# Plans",
  "",
  "<!-- Do not hand-edit. Regenerated by `./scripts/plan-graph.sh generate-md`. -->",
  "",
  "Execution plans are first-class artifacts.",
  "",
  "## Rules",
  "",
  "- Small changes can use lightweight notes in pull requests.",
  "- Anything cross-cutting, risky, or multi-step needs a checked-in execution plan.",
  "- Active plans live in `docs/exec-plans/active/`.",
  "- Completed plans move to `docs/exec-plans/completed/`.",
  "- Plans should be updated when scope or decisions change.",
  "- Pull requests should reference the execution plan they implement.",
  "",
  "## Plan Shape",
  "",
  "Every execution plan should include:",
  "",
  "- Goal",
  "- Why now",
  "- Scope",
  "- Out of scope",
  "- Milestones",
  "- Validation",
  "- Open questions",
  "- Decision log",
  "",
  "## Active Roadmap",
  "",
  "The roadmap is sequenced so foundation, data, product workflows, automation, and commercial readiness can land as independently verifiable slices.",
  "",
];

const FOOTER_LINES: string[] = [
  "",
  "## Sequencing Notes",
  "",
  "- Foundation work should land before features that depend on auth, data, secrets, or the app shell.",
  "- Data contracts and integration boundaries should stabilize before automation or reporting layers rely on them.",
  "- Risky external actions should ship behind approval, audit, and rollback controls before any autopilot behavior is enabled.",
  "- Billing and deployment readiness can land in parallel once the core workspace model is stable.",
  "",
];

export function generatePlansMarkdown(plans: Plan[], repoRoot: string): string {
  const rows = [...plans].sort((a, b) => a.id.localeCompare(b.id));
  const columns: Array<[string, string, string, string]> = rows.map((plan) => {
    const relativePath = path
      .relative(path.join(repoRoot, "docs"), plan.filePath)
      .split(path.sep)
      .join("/");
    const filename = path.basename(plan.filePath);
    return [plan.id, plan.title, `[${filename}](${relativePath})`, plan.phase];
  });

  const widths = [4, 0, 0, 0];
  const headers: [string, string, string, string] = [
    "#",
    "Plan",
    "File",
    "Phase",
  ];
  for (let i = 0; i < headers.length; i += 1) {
    widths[i] = headers[i]!.length;
  }
  for (const row of columns) {
    for (let i = 0; i < row.length; i += 1) {
      const cellLength = row[i]!.length;
      if (cellLength > widths[i]!) widths[i] = cellLength;
    }
  }

  const lines: string[] = [...HEADER_LINES];
  lines.push(formatRow(headers, widths));
  lines.push(
    formatRow(
      widths.map((w) => "-".repeat(w)) as [string, string, string, string],
      widths,
    ),
  );
  for (const row of columns) lines.push(formatRow(row, widths));
  lines.push(...FOOTER_LINES);
  return lines.join("\n");
}

function formatRow(
  cells: [string, string, string, string],
  widths: number[],
): string {
  const padded = cells.map((cell, i) => cell.padEnd(widths[i] ?? cell.length));
  return `| ${padded.join(" | ")} |`;
}
